name: desktop_friendly_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 < 4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_pagination: ^0.0.8
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  image_picker: ^1.1.2
  flutter_pw_validator: ^1.6.0
  intl: ^0.19.0
  dart_amqp: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
